### ISSUE TITLE
Missing `splash.png`

### ISSUE THREAD

**Issue by martoko** [sylGauthier/weiqi#1]
Weiqi does not start, and  complains that it is missing the file `splash.png`.

**Comment by sylGauthier** [comment]
Hi, thank you for your feedback. Are you using the binary build or did you build it yourself?

If the former, make sure the executable is called from its own directory (e.g `cd weiqi-0.0-alpha && ./weiqi`), the data dir path being hardcoded and relative to the executable.

If the latter (you built it yourself), then there was indeed a bug (forgot to add `splash.png` to the texture list to be downloaded by `make`), which should be fixed now, you can `rm -r data && git pull && make` and that should solve it.

**Comment by martoko** [comment]
Yeah, the binary died on me with a SIGILL error, which is why I resorted to building it myself. I can confirm that it does indeed work now.
